[tool.poetry]
name = "reskill-gcp-data-project-retail"
version = "0.1.0"
description = ""
authors = ["JohnR46 <machine.The@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
